# Feature Selection techniques
curse of dimensonality
# Feature Selection-Dropping constant features

In this step we will be removing the features which have constant features which are actually not important for solving the problem statement

In [1]:
#Import pandas to create Dataframe
import pandas as pd
data=pd.DataFrame({"A":[1,2,4,1,2,4],"B":[4,5,6,7,8,9],"C":[0,0,0,0,0,0],"D":[1,1,1,1,1,1]})

In [2]:
data.head()

A  B  C  D
0  1  4  0  1
1  2  5  0  1
2  4  6  0  1
3  1  7  0  1
4  2  8  0  1

# Varience Threshold
Feature selector that removes all low-varience features .

This feature selection algorithim looks only at the feature(X),not the desired outputs(y) and can thus be used for unsupervized learning.in this example all are input features

threshold=0.0 means ,check the feature which having zero varience,remove this fetature and you can see the c and D column has the same value so varience  and s.d and mean almost 0

In [57]:
##I t will zero varience  features
from sklearn.feature_selection import VarianceThreshold
var_thres=VarianceThreshold(threshold=0)
#can change the threshold value to 0.1,0.02,0.3......1.0,2.0........that is actually called quasi constant feature dropping
var_thres.fit(data)


VarianceThreshold(threshold=0)

In [9]:
var_thres.get_support()

array([ True,  True, False, False])

in the output----it means that in the data A and B are true they are not zero varience where Cand D are zero varience remove those feature .So we are pickup those value which are False

In [12]:
data.columns[var_thres.get_support()]#print only the true feature which are not remove

Index(['A', 'B'], dtype='object')

In [10]:
#after do this----take out all my constant column  or which all column get remove will get it over here after this

In [13]:
constant_columns=[column for column in data.columns
                  if column not in data.columns[var_thres.get_support()]]
print(len(constant_columns))

2


In [14]:
#iterate the column name
for feature in constant_columns:
    print(feature)

C
D


In [16]:
data.drop(constant_columns,axis=1)

A  B
0  1  4
1  2  5
2  4  6
3  1  7
4  2  8
5  4  9

# Lets practice with bigger dataset


In [31]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shivadityabaghel05/santandercsv")

#print("Path to dataset files:", path)

In [35]:
df=pd.read_csv('/root/.cache/kagglehub/datasets/shivadityabaghel05/santandercsv/versions/1/santander.csv',nrows=10000)

In [36]:
df.shape

(10000, 371)

In [37]:
df.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   1     2     23                 0.0                      0.0   
1   3     2     34                 0.0                      0.0   
2   4     2     23                 0.0                      0.0   
3   8     2     37                 0.0                    195.0   
4  10     2     39                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                    195.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
0                        0                        0  ...   
1                        0                        0  ...   
2                        0                        0  ...   
3                        0                        0  ...   
4                        0                        0  ...   

   saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     0.0   
2                      0.0                      0.0                     0.0   
3                      0.0                      0.0                     0.0   
4                      0.0                      0.0                     0.0   

   saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   

   saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38  TARGET  
0                     0.0                     0.0   39205.170000       0  
1                     0.0                     0.0   49278.030000       0  
2                     0.0                     0.0   67333.770000       0  
3                     0.0                     0.0   64007.970000       0  
4                     0.0                     0.0  117310.979016       0  

[5 rows x 371 columns]

In [38]:
X=df.drop(labels=['TARGET'],axis=1)
y=df['TARGET']
#we need to do this because varience threshold applied only on the independent features

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
X_train.shape,X_test.shape

((7000, 370), (3000, 370))

# Let's apply variance threshold

In [41]:
var_thres=VarianceThreshold(threshold=0)
var_thres.fit(X_train)

VarianceThreshold(threshold=0)

In [50]:
var_thres.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [44]:
#finding non constant features which are not threshold=0
sum(var_thres.get_support()) #by sum you can see total length of sum

np.int64(284)

So out of 370 we get 284 column

In [51]:
len(X_train.columns[var_thres.get_support()])

284

In [53]:
#find the constant feature
constant_columns=[column for column in X_train.columns
                  if column not in X_train.columns[var_thres.get_support()]]
print(len(constant_columns))

86


In [55]:
#iterate the constant column name which has 0 varience or theeshold 0
for column in constant_columns:
    print(column)

ind_var2_0
ind_var2
ind_var13_medio_0
ind_var13_medio
ind_var18_0
ind_var18
ind_var27_0
ind_var28_0
ind_var28
ind_var27
ind_var34_0
ind_var34
ind_var41
ind_var46_0
ind_var46
num_var13_medio_0
num_var13_medio
num_var18_0
num_var18
num_var27_0
num_var28_0
num_var28
num_var27
num_var34_0
num_var34
num_var41
num_var46_0
num_var46
saldo_var13_medio
saldo_var18
saldo_var28
saldo_var27
saldo_var34
saldo_var41
saldo_var46
delta_imp_amort_var18_1y3
delta_imp_amort_var34_1y3
delta_imp_reemb_var17_1y3
delta_imp_reemb_var33_1y3
delta_imp_trasp_var17_out_1y3
delta_imp_trasp_var33_out_1y3
delta_num_reemb_var17_1y3
delta_num_reemb_var33_1y3
delta_num_trasp_var17_out_1y3
delta_num_trasp_var33_out_1y3
imp_amort_var18_hace3
imp_amort_var18_ult1
imp_amort_var34_hace3
imp_amort_var34_ult1
imp_var7_emit_ult1
imp_reemb_var13_hace3
imp_reemb_var17_hace3
imp_reemb_var17_ult1
imp_reemb_var33_hace3
imp_reemb_var33_ult1
imp_trasp_var17_in_hace3
imp_trasp_var17_out_hace3
imp_trasp_var17_out_ult1
imp_trasp_var33_i

In [56]:
X_train.drop(constant_columns,axis=1)

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
7681  15431     2     42               840.0                  4477.02   
9031  18181     2     31                 0.0                    52.32   
3691   7411     2     51                 0.0                     0.00   
202     407     2     36                 0.0                     0.00   
5625  11280     2     23                 0.0                     0.00   
...     ...   ...    ...                 ...                      ...   
9225  18564     2     33                 0.0                     0.00   
4859   9723     2     24                 0.0                     0.00   
3264   6557     2     24                 0.0                     0.00   
9845  19796     2     38                 0.0                     0.00   
2732   5441     2     23                 0.0                     0.00   

      imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  \
7681                  4989.54                      0.0   
9031                    52.32                      0.0   
3691                     0.00                      0.0   
202                      0.00                      0.0   
5625                     0.00                      0.0   
...                       ...                      ...   
9225                     0.00                      0.0   
4859                     0.00                      0.0   
3264                     0.00                      0.0   
9845                     0.00                      0.0   
2732                     0.00                      0.0   

      imp_op_var40_comer_ult3  imp_op_var40_efect_ult1  \
7681                      0.0                        0   
9031                      0.0                        0   
3691                      0.0                        0   
202                       0.0                        0   
5625                      0.0                        0   
...                       ...                      ...   
9225                      0.0                        0   
4859                      0.0                        0   
3264                      0.0                        0   
9845                      0.0                        0   
2732                      0.0                        0   

      imp_op_var40_efect_ult3  ...  saldo_medio_var29_ult3  \
7681                        0  ...                     0.0   
9031                        0  ...                     0.0   
3691                        0  ...                     0.0   
202                         0  ...                     0.0   
5625                        0  ...                     0.0   
...                       ...  ...                     ...   
9225                        0  ...                     0.0   
4859                        0  ...                     0.0   
3264                        0  ...                     0.0   
9845                        0  ...                     0.0   
2732                        0  ...                     0.0   

      saldo_medio_var33_hace2  saldo_medio_var33_hace3  \
7681                      0.0                      0.0   
9031                      0.0                      0.0   
3691                      0.0                      0.0   
202                       0.0                      0.0   
5625                      0.0                      0.0   
...                       ...                      ...   
9225                      0.0                      0.0   
4859                      0.0                      0.0   
3264                      0.0                      0.0   
9845                      0.0                      0.0   
2732                      0.0                      0.0   

      saldo_medio_var33_ult1  saldo_medio_var33_ult3  saldo_medio_var44_hace2  \
7681                     0.0                     0.0                      0.0   
9031                     0.0                     0.0                      0.0   
3691                     0.0                     0.0 